"=======================
"      ***********
"         vimrc
"      ***********
"  github.com/miikkani
"=======================
                               

" Settings for GUI 
if has("gui_running")
" set theme
colorscheme slate
" font
set guifont=JetBrains_Mono:W300:h11
endif
" 


filetype indent plugin on

syntax on

highlight Comment gui=italic "cterm=italic
highlight ColorColumn ctermbg=7
set hlsearch
set autoindent

"show vertical line
set colorcolumn:80

"show information
set ruler

"show relative line numbers
set rnu

"text encoding
set encoding=utf-8

" use LF line endings
set fileformats=unix,dos
set fileformat=unix

" set tabs, follows java convention
set tabstop=8
set shiftwidth=4
set softtabstop=0
set expandtab
set smarttab

